# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7cd46e2dc135275401ef9139d9de09d9c336e5a2df579b65b349463777ce7c4ee9ba8e0c37a563cd98b1ed3ad22e8b15e311f65d15f5bd8223990018294a593e

test:
  secret_key_base: f01a074574f991c433b6fe9d9625012fe89edbd376b1fc80aaa384ddbe2dac6ef94ff902e8a1ca35fcd3c78d6abad52c65d02de59434f4b6f7c2f48f35115b5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
